name: CI & CD

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*-bullseye-*"
      - "*-debian-*"
      - "*-alpine*-*"

env:
  DOCKER_BUILDKIT: 1

jobs:
  build-test-publish:
    name: Build, Test, & Publish
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        architecture: [alpine, debian, bullseye]
    steps:
      - name: Check if deployment
        if: ${{ github.ref == 'refs/heads/master' || (contains(github.ref, 'tags') && contains(github.ref, matrix.architecture)) }}
        run: echo "IS_DEPLOYMENT='true'" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Get Image Name
        run: echo "IMAGE_NAME=$(echo '${{ github.repository }}' | awk '{print tolower($0)}')/${{ matrix.architecture }}" >> $GITHUB_ENV
      - name: Build & Test
        id: build-docker-image-using-cache
        uses: whoan/docker-build-with-cache-action@v5.11.0
        timeout-minutes: 5
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          image_name: ${{ env.IMAGE_NAME }}
          image_tag: ${{ github.sha }}
          push_git_tag: true
          dockerfile: Dockerfile.${{ matrix.architecture }}
          build_extra_args: --build-arg BUILDKIT_INLINE_CACHE=1
      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.0.17
        with:
          image-ref: ${{ steps.build-docker-image-using-cache.outputs.FULL_IMAGE_NAME }}:${{ github.sha }}
          format: template
          template: "@/contrib/sarif.tpl"
          output: trivy-results.sarif
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: trivy-results.sarif
      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.0.17
        with:
          image-ref: ${{ steps.build-docker-image-using-cache.outputs.FULL_IMAGE_NAME }}:${{ github.sha }}
          exit-code: 1
          severity: CRITICAL
          format: table
      - name: Build and publish Docker Image to GitHub Packages Registry
        uses: VaultVulp/gp-docker-action@1.1.8
        if: ${{ env.IS_DEPLOYMENT == 'true' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: rails
          image-tag: latest-${{ matrix.architecture }}
          dockerfile: Dockerfile.${{ matrix.architecture }}
          custom-args: --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from=${{ steps.build-docker-image-using-cache.outputs.FULL_IMAGE_NAME }}:${{ github.sha }}
