name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  DOCKER_BUILDKIT: 1

jobs:
  vulnerability-scanning:
    name: Vulnerability Scanning
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      IMAGE_NAME: ${{ github.repository }}:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Get Image Name
        run: echo "IMAGE_NAME=$(echo '${{ github.repository }}' | awk '{print tolower($0)}')/default" >> $GITHUB_ENV
      - name: Build & Test
        id: build-docker-image-using-cache
        uses: whoan/docker-build-with-cache-action@v5.11.0
        timeout-minutes: 3
        with:
          username: ${{ github.actor }}
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: ${{ env.IMAGE_NAME }}
          image_tag: ${{ github.sha }}
          push_git_tag: true
          build_extra_args: "--build-arg BUILDKIT_INLINE_CACHE=1"
      - name: Scan Image for Vulnerabilities
        uses: docker://docker.io/aquasec/trivy:0.2.1
        timeout-minutes: 5
        with:
          args: --cache-dir /var/lib/trivy --severity "CRITICAL,HIGH" --exit-code 1 --no-progress ${{ steps.build-docker-image-using-cache.outputs.FULL_IMAGE_NAME }}:${{ github.sha }}
